### ISSUE TITLE
Issue when all blocks are not in use. 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/epi-dsp-tesira#7] opened 2020-06-12 21:30 UTC
[16:10:37.000]App 2:Creating DSP Objects
[16:10:37.000]App 2:[TesiraDsp-1] Props Exists
[16:10:37.000]App 2:[TesiraDsp-1] Here's the props string {
  "control": {
    "deviceReadyResponsePattern": "",
    "endOfLineString": "\n",
    "method": "ssh",
    "tcpSshProperties": {
      "AutoReconnectIntervalMs": 100000,
      "address": "192.168.1.136",
      "autoReconnect": true,
      "password": "default",
      "port": 22,
      "username": "default"
    }
  },
  "switcherControlBlocks": {
    "Switcher01": {
      "enabled": true,
      "type": "router",
      "index1": 1,
      "label": "SOURCE1",
      "switcherInstanceTag": "METERROUTER"
    }
  }
}
[16:10:37.000]App 2:ERROR: Creating device TesiraDsp-1. Skipping device. 
System.ArgumentNullException: Value can not be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Tesira_DSP_EPI.TesiraDsp.CreateDspObjects()
   at Tesira_DSP_EPI.TesiraDsp..ctor(String key, String name, IBasicCommunication comm, DeviceConfig dc)
   at Tesira_DSP_EPI.TesiraDsp.BuildDevice(DeviceConfig dc)
   at PepperDash.Essentials.Core.DeviceFactory.GetDevice(DeviceConfig dc)
   at PepperDash.Essentials.ControlSystem.LoadDevices()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()

**Comment by TrevorPayne** [comment] 2023-02-17 05:36
Marking as closed - Unable to reproduce - also - this issue is **very old**

**Closed by TrevorPayne** 2023-02-17 05:36 UTC
