### ISSUE TITLE
[BUG]-Fader keys are created with two dashes in a row. [dsp--Fader02]

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/epi-dsp-tesira#64] opened 2022-08-17 16:33 UTC
**Expected behavior**
Should be a single dash Device key-faderkey

**Comment by TrevorPayne** [comment] 2023-02-17 04:39
This is working as intended and as documented - this will not be modified in this plugin.  Branch it if you want this functionality.

Closing issue

**Closed by TrevorPayne** 2023-02-17 04:39 UTC
Labels: bug
