### ISSUE TITLE
[BUG]-Hitting a null exception when restarting essentials. 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/epi-dsp-tesira#67] opened 2022-08-27 11:59 UTC
**Describe the bug**

**Stacktrace**

Include a stack trace of the exception if possible.
```
469. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  # Exception:SendProgramEventToControlSystem - System.Reflection.TargetInvocationException: TargetInvocationException ---> System.NullReferenceException: NullReferenceException
   at Tesira_DSP_EPI.TesiraDsp.CrestronEnvironment_ProgramStatusEventHandler(ePr470. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  # ogramStatusEventType programEventType)
   at Crestron.SimplSharp.CrestronEnvironment.SetProgramEvent(eProgramStatusEventType programEventType)
   at System.Reflection.RuntimeMethodInfo.InternalInvoke(RuntimeMethodInfo rtmi, Object obj, BindingFlags invo471. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  # keAttr, Binder binder, Object parameters, CultureInfo culture, Boolean isBinderDefault, Assembly caller, Boolean verifyAccess, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.InternalInvoke(Object obj, BindingFlags invokeAttr, Binder472. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  #  binder, Object[] parameters, CultureInfo culture, Boolean verifyAccess, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Syst473. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  # em.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Crestron.SimplSharpPro.CrestronControlSystem.OnProgramEventCallback(eProgramStatusEventType programEventType)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.ak(eProgramSta474. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  # tusEventType A_0)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.ap(Object A_0)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.b()

   at System.Reflection.RuntimeMethodInfo.InternalInvoke(Object obj, BindingFlags invokeAttr, Bin475. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  # der binder, Object[] parameters, CultureInfo culture, Boolean verifyAccess, StackCrawlMark& stackMark)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at S476. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  # ystem.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Crestron.SimplSharpPro.CrestronControlSystem.OnProgramEventCallback(eProgramStatusEventType programEventType)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.ak(eProgram477. Error: SimplSharpPro.exe # 2022-08-27 07:56:20  # StatusEventType A_0)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.ap(Object A_0)
   at Crestron.SimplSharpProInternal.SimplSharpProManager.b()
```

**To Reproduce**
Restart essentials program

**Comment by TrevorPayne** [comment] 2023-02-17 05:33
Resolved in latest release (I think - I've been unable to reproduce it again )

**Closed by TrevorPayne** 2023-02-17 05:33 UTC
Labels: bug
